# Generated by Django 3.1.5 on 2021-01-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0002_auto_20210104_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Data Type')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='column',
            name='data_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.ProtectedError, to='csv_generator.datatype', verbose_name='Data Type'),
        ),
    ]
