# Generated by Django 3.1.5 on 2021-01-05 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0003_auto_20210105_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='columns',
        ),
        migrations.AddField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.ProtectedError,
                to='csv_generator.schema',
                verbose_name='Schema'),
        ),
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.ProtectedError,
                to='csv_generator.datatype',
                verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(
                max_length=200,
                unique=True,
                verbose_name='Column name'),
        ),
    ]
