# Generated by Django 3.1.5 on 2021-01-06 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csv_generator', '0004_auto_20210105_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='schema',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='csv_generator.schema', verbose_name='Schema'),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('schema', 'order')},
        ),
    ]
