# Generated by Django 3.1.5 on 2021-01-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0005_auto_20210106_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Column name'),
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Processing', 'Processing')], default='Processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csv_generator.schema', verbose_name='Schema')),
            ],
        ),
    ]
