# Generated by Django 3.1.5 on 2021-01-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0006_auto_20210106_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='rows',
            field=models.PositiveIntegerField(default=10, verbose_name='Rows'),
            preserve_default=False,
        ),
    ]
