# Generated by Django 3.1.5 on 2021-01-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0008_auto_20210106_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataType',
        ),
        migrations.AlterField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('Full name', 'Full name'), ('Job', 'Job'), ('Address', 'Address'), ('Phone number', 'Phone number')], max_length=20),
        ),
    ]
