# Generated by Django 3.1.5 on 2021-01-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csv_generator', '0009_auto_20210106_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='start_from',
            field=models.IntegerField(default=18, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='column',
            name='to',
            field=models.IntegerField(default=60, verbose_name='To'),
        ),
    ]
